# Manufacturers

### List manufacturers
GET http://localhost:8100/api/manufacturers/

### Create a manufacturer
POST http://localhost:8100/api/manufacturers/

{
    "name": "Chrysler"
}

### Get a specific manufacturer
GET http://localhost:8100/api/manufacturers/1/

### Update a specific manufacturer
PUT http://localhost:8100/api/manufacturers/1/

{
    "name": "Dodge"
}

### Delete a specific manufacturer
DELETE http://localhost:8100/api/manufacturers/2/

# Vehicle Models

### List vehicle models	
GET http://localhost:8100/api/models/

### Create a vehicle model
POST http://localhost:8100/api/models/

{
    "name": "Sebring",
    "picture_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Chrysler_Sebring_front_20090302.jpg/320px-Chrysler_Sebring_front_20090302.jpg",
    "manufacturer_id": 1
}

### Get a specific vehicle model
GET http://localhost:8100/api/models/1/

### Update a specific vehicle model
PUT http://localhost:8100/api/models/1/

{
    "name": "Sebring",
    "picture_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Chrysler_Sebring_front_20090302.jpg/320px-Chrysler_Sebring_front_20090302.jpg"
}

### Delete a specific vehicle model	
DELETE http://localhost:8100/api/models/1/

# Automobile

### List automobiles	
GET	http://localhost:8100/api/automobiles/

### Create an automobile
POST http://localhost:8100/api/automobiles/

{
    "color": "red",
    "year": 2012,
    "vin": "1C3CC5FB2AN120174",
    "model_id": 1
}

### Get a specific automobile
GET	http://localhost:8100/api/automobiles/1C3CC5FB2AN120174/

### Update a specific automobile	
PUT	http://localhost:8100/api/automobiles/1C3CC5FB2AN120174/

{
    "color": "red",
    "year": 2012,
    "sold": true
}

### Delete a specific automobile
DELETE	http://localhost:8100/api/automobiles/1C3CC5FB2AN120174/

