volumes:
    beta-data:
services:
    react:
        image: node:lts-bullseye
        working_dir: /app
        volumes:
            - ./ghi/app:/app
        ports:
            - "5173:5173"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
        entrypoint: /bin/bash -c "npm install && npm run dev -- --host"
    database:
        image: postgres:14.2-bullseye
        volumes:
            - beta-data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES=design,sales,service
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    design-api:
        build:
            context: ./design/api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./design/api:/app
        depends_on:
            - database
        environment:
            DATABASE_URL: postgres://design:password@database:5432/design
            WAIT_HOSTS: database:5432
            WAIT_TIMEOUT: 240
            PEXELS_API_KEY: ${PEXELS_API_KEY}
