# Generated by Django 5.0.7 on 2024-08-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_rest", "0002_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
