# Generated by Django 5.0.7 on 2024-08-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
