# Generated by Django 5.0.7 on 2024-08-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0002_alter_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesperson",
            name="employee_id",
            field=models.CharField(max_length=100),
        ),
    ]
